version: '3.8'
services:
  frontend:
    build: 
      context: ..
      dockerfile: infrastructure/images/teambrains-frontend/Dockerfile
    container_name: teambrains-frontend
    ports:
      - "5173:5173"

  backend:
      build:
        context: ..
        dockerfile: infrastructure/images/teambrains-backend/Dockerfile
      container_name: teambrains-backend
      ports:
        - "5001:5001"
      environment:
        - FLASK_ENV=development
        - FLASK_APP=app.py

  database:
    image: postgres:15
    container_name: teambrains-database
    environment:
      POSTGRES_DB: teambrains
      POSTGRES_USER: teambrains
      POSTGRES_PASSWORD: teambrains
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: teambrains-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: teambrains
    ports:
      - "5050:80"