version: '3.8'
services:
  frontend:
    build: 
      context: ..
      dockerfile: infrastructure/images/teambrains-frontend/Dockerfile
    container_name: teambrains-frontend
    ports:
      - "5173:5173"

  backend:
      build:
        context: ..
        dockerfile: infrastructure/images/teambrains-backend/Dockerfile
      container_name: teambrains-backend
      ports:
        - "5000:5000"
      environment:
        - FLASK_ENV=development
        - FLASK_APP=app.py